### PR TITLE
Migrated to sonar v 8.2.0.32929 API

### PR DESCRIPTION
**Pull request by javamachr**
On top of previous PR added even newer API compatibility

### CODE REVIEW

**Comment by javamachr** [comment]
This is a followup PR for https://github.com/gabrie-allaigre/sonar-gitlab-plugin/pull/253 . Also released from my repo here https://github.com/javamachr/sonar-gitlab-plugin/releases/tag/4.2.0

**Comment by shouldnotappearcalm** [comment]
@javamachr I will try it immediately, thank you pr

**Comment by shouldnotappearcalm** [comment]
I use `mvn --batch-mode verify sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.max_major_issues_gate=0 -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.branch.name=$CI_COMMIT_REF_NAME`

I have installed the 4.2 version you provided, but the error is as follows when executing the command in gitlab ci

```
[INFO] Executing post-job 'GitLab Commit Issue Publisher'
[INFO] Will execute CommitPublishPostJob of GitlabPlugin.
[INFO] GitLab plugin is enabled
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.281 s
[INFO] Finished at: 2020-04-27T16:09:07Z
[INFO] Final Memory: 57M/402M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project test-auto: null: MojoExecutionException: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
ERROR: Job failed: exit code 1```

**Comment by shouldnotappearcalm** [comment]
It can work normally, thank you very much

**Pull request closed without merging**
