### PR TITLE
Make sure that ReporterBuilder is available during batch

### PR DESCRIPTION
**Pull request by lukaspj**
See #213

### CODE REVIEW

**Comment by lukaspj** [comment]
If you don't want to build it locally, here is a built version of this branch:
[sonar-gitlab-plugin-4.1.0-SNAPSHOT.zip](https://github.com/gabrie-allaigre/sonar-gitlab-plugin/files/2816503/sonar-gitlab-plugin-4.1.0-SNAPSHOT.zip)

**Comment by DennisHartrampf** [comment]
Today I upgraded our SonarQube to 7.6 and we are facing this issue now. I am glad, it is already fixed, and would love to see a release soon.

**Comment by ripper2hl** [comment]
Thanks !

this a link for manual installation

https://docs.sonarqube.org/latest/setup/install-plugin/

captura de pantalla de 2019-02-13 18-01-25

merge this please

**Comment by alephtwo** [comment]
Can we get a status update on this? I'd rather not manage my own build of the plugin with this fix in, but it's a serious blocker for us upgrading Sonarqube.

**Comment by alessiofachechi** [comment]
I've installed the snapshot and the analysis ends with success, but the pipeline fails with the following output:
```
11:48:10.028 DEBUG: Post-jobs : GitLab Commit Issue Publisher
11:48:10.028 INFO: Executing post-job 'GitLab Commit Issue Publisher'
11:48:17.568 INFO: ------------------------------------------------------------------------
11:48:17.568 INFO: EXECUTION FAILURE
11:48:17.568 INFO: ------------------------------------------------------------------------
11:48:17.569 INFO: Total time: 15.907s
11:48:17.741 INFO: Final Memory: 24M/324M
11:48:17.741 INFO: ------------------------------------------------------------------------
11:48:17.741 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
	at com.talanlabs.sonar.plugins.gitlab.GitLabApiV4Wrapper.createOrUpdateSonarQubeStatus(GitLabApiV4Wrapper.java:211)
	at com.talanlabs.sonar.plugins.gitlab.CommitFacade.createOrUpdateSonarQubeStatus(CommitFacade.java:128)
	at com.talanlabs.sonar.plugins.gitlab.CommitPublishPostJob.execute(CommitPublishPostJob.java:112)
	at org.sonar.scanner.postjob.PostJobWrapper.execute(PostJobWrapper.java:49)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:48)
	at org.sonar.scanner.postjob.PostJobsExecutor.execute(PostJobsExecutor.java:39)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:376)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:126)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
ERROR: Job failed: exit status 1
```

Maybe anything related to the reporting?

**Comment by don-vip** [comment]
@gabrie-allaigre Can you please merge this fix and make a new release?

**Comment by dmarin** [comment]
:clap: :clap: thanks!!

**Pull request merged**
