### PR TITLE
Use official GitLab API.

### PR DESCRIPTION
**Pull request by johnou**
Looks like the Github and talanlabs (which is inaccessible and doesn't allow me to sign up) are out of sync.

### CODE REVIEW

**Comment by johnou** [comment]
@simonbrandhof if I recreate sonar-gitlab forked from https://github.com/SonarSource/sonar-github would you consider pulling it into https://github.com/SonarSource?

**Comment by gabrie-allaigre** [comment]
Thanks, for use official api.

**Comment by simonbrandhof** [comment]
@johnou the SonarSource repository is for the projects developed and maintained by SonarSource, so no, sonar-gitlab can't be moved there.

That's not a problem so far as non-SonarSource plugins can still be listed in Update Center. See https://docs.sonarqube.org/display/DEV/Deploying+to+Update+Center for more details.

**Comment by johnou** [comment]
@simonbrandhof okay, so the SonarSource team is not planning on introducing / supporting GitLab officially in the foreseeable future?

**Comment by simonbrandhof** [comment]
@johnou exact, it is not planned for the time being.

**Comment by johnou** [comment]
@simonbrandhof thanks, if things change would you kindly reach out to me?

**Comment by johnou** [comment]
@gabrie-allaigre what's the best way for us to collaborate on this project? Are you interested in futher development? Should I continue sending pull requests to this repository?

**Comment by gabrie-allaigre** [comment]
Hi,

Are you sure a GitLab API java is official ? Because I think that a GitLabAPI.java is very very big and some methods are redundant.

Soon I will add unit test for pass quality gate in sonar and change gitlab api for v4 version. (v3 is soon deprecated)

Thanks

**Comment by johnou** [comment]
@gabrie-allaigre woah.. https://github.com/timols/java-gitlab-api not official at all, how did that they even get that into central Maven? I was under the impression that you must own the domain / prove ownership.

**Comment by johnou** [comment]
I'll create a new pull request with only the improvements.

**Comment by gabrie-allaigre** [comment]
@johnou Sorry but to have a domain on the central is easy, just do a issue in sonatype jira. Domain is not verify. (I'm domain in central for my company). 
In https://about.gitlab.com/applications/#api-clients, this is 2 plugins for client api java.

**Pull request closed without merging**
