### PR TITLE
Supply SonarQube GitLab avatar.

### PR DESCRIPTION
**Pull request by johnou**

### CODE REVIEW

**Comment by gabrie-allaigre** [comment]
Hi,
Sorry but images are used by the old version, there are direct links with the repo. They can not be deleted

**Comment by johnou** [comment]
@gabrie-allaigre aha you're right, I'll revert that and just leave the avatar.

**Comment by johnou** [comment]
@gabrie-allaigre updated.

**Comment by gabrie-allaigre** [comment]
Why add badge ?

**Comment by johnou** [comment]
@gabrie-allaigre so people can upload it directly to the SonarQube profile in GitLab.

**Comment by johnou** [comment]
sq

**Comment by johnou** [comment]
Attaching fullsize image kindly provided by one of our gfx people.

sonar2

**Comment by johnou** [comment]
I updated the sonarqube_avatar.png too with bicubic resizing.

**Pull request merged**
